### ISSUE TITLE
Change rulesets

### ISSUE THREAD

**Issue by matneves** [SublimeLinter/SublimeLinter-phpmd#18]
Hi, how can I change the rulesets?

**Comment by braver** [comment]
Not sure, but probably  by setting [args](http://www.sublimelinter.com/en/stable/linter_settings.html#args): https://phpmd.org/documentation/index.html

**Comment by kaste** [comment]
There is a actually a settings `rulesets` for this. (Default value: 'cleancode,codesize,controversial,design,naming,unusedcode'.) 

```
linters:
	phpmd:
		rulesets: 'foo,bar'
```

in your settings should do it.

**Comment by matneves** [comment]
Thanks!
