### ISSUE TITLE
Intermittent error when saving

### ISSUE THREAD

**Issue by JoyceBabu** [SublimeLinter/SublimeLinter-phpmd#21]
The linter is failing intermittently with the following error

I think the temporary file is being delete before the linting process is completed.

PHP MD Version - 2.6.0
SublimeLinter-phpmd Version - master

> SublimeLinter: WARNING: phpmd reported errors coming from '/private/var/folders/3s/fdq_1vdn3sb27vdcq2qwxnvc0000gn/T/tmpabhhk0.php'. However, reading that file raised:
>   [Errno 2] No such file or directory: '/private/var/folders/3s/fdq_1vdn3sb27vdcq2qwxnvc0000gn/T/tmpabhhk0.php'.

If I change `cmd = ('phpmd', '${temp_file}', 'text')` to `cmd = ('phpmd', '${file}', 'text')`, the error goes away. But then I have to save the file to see the lint errors.

**Comment by kaste** [comment]
Interesting, can you post the actual phpmd output?

**Comment by JoyceBabu** [comment]
The error is due to a symbolic link handling in SublimeLinter. I will send a PR soon to SublimeLinter.
