### ISSUE TITLE
install pear.phpmd.org error

### ISSUE THREAD

**Issue by Dev-Jabin** [SublimeLinter/SublimeLinter-phpmd#23]
Discovering channel pear.phpmd.org over http:// failed with message: channel-add: Cannot open "http://pear.phpmd.org/channel.xml" (Connection to `pear.phpmd.org:80' failed: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known)
Trying to discover channel pear.phpmd.org over https:// instead
Discovery of channel "pear.phpmd.org" failed (channel-add: Cannot open "https://pear.phpmd.org/channel.xml" (Connection to `ssl://pear.phpmd.org:443' failed: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known))

Discovering channel pear.pdepend.org over http:// failed with message: channel-add: Cannot open "http://pear.pdepend.org/channel.xml" (Connection to `pear.pdepend.org:80' failed: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known)
Trying to discover channel pear.pdepend.org over https:// instead
Discovery of channel "pear.pdepend.org" failed (channel-add: Cannot open "https://pear.pdepend.org/channel.xml" (Connection to `ssl://pear.pdepend.org:443' failed: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known))

Attempting to discover channel "phpmd"...
Attempting fallback to https instead of http on channel "phpmd"...
unknown channel "phpmd" in "phpmd/PHP_PMD"
invalid package name/package file "phpmd/PHP_PMD"
install failed

**Comment by braver** [comment]
What is this? Spam? Or is your phpmd trying to do something? Does linting work from the command line?

**Comment by progmusike** [comment]
I have this same issue, I'm trying to run the command in W10 as admin, inside the c:\xampp\php\. My php comes from the XAMPP distribution. This is the last step to setup the linter. So frustrating.

When I run the command from the pear folder it opens a prompt. 
![screengrab](https://user-images.githubusercontent.com/37005835/73311541-91eb9480-41db-11ea-85b4-5e4106ce3b16.png)

**Comment by braver** [comment]
This repo is just about the wrapper for SublimeLinter. All questions about the linter utility itself: http://phpmd.org/support/index.html
