### ISSUE TITLE
WSL : The given file "[...]" does not exist.

### ISSUE THREAD

**Issue by lechat69** [SublimeLinter/SublimeLinter-phpmd#24]
I'm using WSL on Windows 10, with phpmd installed on a Debian.
I can't get the PHPMD error to display.
This is my debug logs :

> C:\Windows\System32\wsl.EXE phpmd c:\users\benjamin\appdata\local\temp\tmpiv99cg.php text cleancode,codesize,design,unusedcode
> SublimeLinter: #3 linter.py:1202      phpmd: output: The given file "c:usersbenjaminappdatalocaltemptmpiv99cg.php" does not exist.
> SublimeLinter: #3 linter.py:1254      phpmd: No match for line: 'The given file "c:usersbenjaminappdatalocaltemptmpiv99cg.php" does not exist.'

I think my Debian can't access to the temp file (it seams logic), but I don't understand why my others linter (php and phpcs) can...

Is there a way to get it to work correctly with SublimeLinter-phpmd ?

**Comment by kaste** [comment]
Wsl is not supported until someone writes code to transform paths esp. file paths back and forth.

As you can see from the logs the path phpmd sees is corrupt.

**Comment by lechat69** [comment]
Yes, I've seen it. What I don't understand, is how Sublimelinter-php and Sublimelinter-phpcs are doing this

**Comment by kaste** [comment]
They don't read a file but from stdin probably.

**Comment by kaste** [comment]
Closing.  Stale as nobody seems to write code for WSL.
