### ISSUE TITLE
Inc file extensions

### ISSUE THREAD

**Issue by nkoporec** [SublimeLinter/SublimeLinter-phpmd#25]
Is there a way to setup this package so that phpmd works with .inc,.module... extensions? Currently for me it only works with .php files.

**Comment by kaste** [comment]
Hm, should be possible. In an editor the extension of a file is irrelevant, what matters is the syntax and scopes from the syntax highlighter. 

Open such a file and at row 0 col 0 press Ctrl+shift+alt+p to display the scope. Compare that to the php files. And probably post it here, or copy it to the selector setting in the SublimeLinter settings.

**Comment by braver** [comment]
You basically tell Sublime Text to open files with these extension with the PHP syntax. SublimeLinter doesn't care about filename, as kaste mentions it's the syntax that matters.

**Comment by nkoporec** [comment]
I setup the selectors in linter settings but it still does not work for file extensions such as .module,.theme.It now works for inc files though. Thanks!
