### ISSUE TITLE
Ruleset override doesn't appear to work

### ISSUE THREAD

**Issue by tmoitie** [SublimeLinter/SublimeLinter-phpmd#4]
SublimeLinter settings - I've overwritten rulesets to not include cleancode (which is not a default phpmd ruleset):
```
            "phpmd": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "rulesets": "codesize,controversial,design,naming,unusedcode"
            },
```

But the linter includes the default rulesets line:
```
SublimeLinter: phpmd: test.php ['phpmd', '[pathtofile]/test.php', 'text', 'cleancode,codesize,controversial,design,naming,unusedcode'] 
SublimeLinter: phpmd output:
Cannot find specified rule-set "cleancode". 
```

**Comment by Nessworthy** [comment]
Issue has been ongoing for nearly 2 years, is there any hope of getting it fixed?

**Comment by Nessworthy** [comment]
Actually, I've just discovered that the comma-seperated list of rulesets are passed directly into phpmd as an argument.
Because of this, you can replace the `rulesets` setting value with the absolute path to a phpmd xml file which you can then use to exclude or otherwise customize your rulesets.

**Comment by ajmichels** [comment]
I haven't been able to reproduce this issue. Specifying a new `ruleset` in settings seems to work fine including specifying a ruleset file as described by @Nessworthy.
