### ISSUE TITLE
Errors not showing

### ISSUE THREAD

**Issue by Baira** [SublimeLinter/SublimeLinter-phpmd#7]
Hi,
Thank you for the great job.
Let's consider this code (just an example) :
<code>
<?php
    public $helpers = array('Session', 'Html', 'Form', 'Text', 'Date')
    public $components = array('Session', 'DebugKit.Toolbar', 'RequestHandler');
?>
</code>

phpmd linter wont show this error even if i get it in console :

<code>
/tmp/tmplwbmsb.php  -   Unexpected token: public, line: 2, col: 2, file: /tmp/tmplwbmsb.php.
</code>

Why no marker is present in line 2 and the error doesn't show in status bar ?

**Comment by sourc7** [comment]
Same here, Baira

**Comment by ajmichels** [comment]
I was able to reproduce this issue with the latest version of `phpmd` (2.4.1) and the latest version of `SublimeLinter-phpmd` (1.1.0).

```php
<?php

    public $helpers = array('Session', 'Html', 'Form', 'Text', 'Date');

    public $components = array('Session', 'DebugKit.Toolbar', 'RequestHandler');
```

```text
SublimeLinter: phpmd: <unsaved> ['/Users/aj/bin/phpmd', '@', 'text', 'cleancode,codesize,controversial,design,naming,unusedcode'] 
SublimeLinter: phpmd output:

/private/var/folders/r9/t9cdt__x7c98rwd3d032fcfw0000gn/T/SublimeLinter3-aj/untitled.php	-	Unexpected token: public, line: 3, col: 5, file: /private/var/folders/r9/t9cdt__x7c98rwd3d032fcfw0000gn/T/SublimeLinter3-aj/untitled.php. 
```

**Comment by kaste** [comment]
Unlikely that something will happen here, so I'm closing.
