### ISSUE TITLE
Exclude rule ref option

### ISSUE THREAD

**Issue by w0rldart** [SublimeLinter/SublimeLinter-phpmd#9]
Having the default rulesets

    "rulesets": "cleancode,codesize,controversial,design,naming,unusedcode"

Is there anyway of applying exclusion to any of those rules? Just like it can be added in a ruleset filet:

    <rule ref="rulesets/cleancode.xml">
        <exclude name="BooleanArgumentFlag" />
    </rule>

?

**Comment by ajmichels** [comment]
I think the solution here is to create a ruleset file and then point the linter at that file.

**Comment by ajmichels** [comment]
See the PHPMD documentation for information on how to create ruleset files. https://phpmd.org/documentation/creating-a-ruleset.html

You can then set the path to the file in your gobal or project settings.

Here is an example of a project setting:

```json
{
    "SublimeLinter": {
        "linters": {
            "phpmd": {
                "rulesets": "${project}/phpmd.xml"
            }
        }
    } 
}
```
